# Base configuration
permalink: /:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
pygments: true

# Kramdown options
kramdown:
  input: GFM

# Title
name: Capital Framework
subtitle: Everything you wanted to know about Capital Framework

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/capital-framework'

# Author/Organization info to be displayed in the templates
author:
  name: The CFPB
  url: http://cfpb.github.io/

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: assets/img/logo.png
logoalt: The Consumer Financial Protection Bureau

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Nice to meet you
  url: index.html
  internal: true
- text: About the components
  url: components/
  internal: true
- text: About the demo/workflow
  url: cf-demo/
  internal: true
- text: Roadmap
  url: roadmap/
  internal: true
- text: Contributing
  url: contributing/
  internal: true

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: capital-framework
  description: The workflow/example project
  url: https://github.com/cfpb/capital-framework
